[package]
name = "cpx"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
home = "0.5.9"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
